blueprints = [
  "Metallofullerene Plating",
  "Electromechanical Interface Nexus",
  "Optimized Nano-Engines",
  "Warfare Computation Core",
  "Fulleroferrocene Power Conduits",
  "Reconfigured Subspace Calibrator",
  "Fullerene Intercalated Sheets",
  "Self-Assembling Nanolattice",
  "R.A.M.- Starship Tech",
  "PPD Fullerene Fibers",
  "Fulleroferrocene",
  "Lanthanum Metallofullerene",
  "Graphene Nanoribbons",
  "Fullerene Intercalated Graphite",
  "Scandium Metallofullerene",
  "Methanofullerene",
  "Carbon-86 Epoxy Resin",
  "C3-FTM Acid",
]
