-- Your SQL goes here

ALTER TABLE "agtAgentTypes" RENAME COLUMN "agentTypeID" to agent_type_id;
ALTER TABLE "agtAgentTypes" RENAME COLUMN "agentType" to agent_type;
ALTER TABLE "agtAgents" RENAME COLUMN "agentID" to agent_id;
ALTER TABLE "agtAgents" RENAME COLUMN "divisionID" to division_id;
ALTER TABLE "agtAgents" RENAME COLUMN "corporationID" to corporation_id;
ALTER TABLE "agtAgents" RENAME COLUMN "locationID" to location_id;
ALTER TABLE "agtAgents" RENAME COLUMN "agentTypeID" to agent_type_id;
ALTER TABLE "agtAgents" RENAME COLUMN "isLocator" to is_locator;
ALTER TABLE "agtAgentsInSpace" RENAME COLUMN "agentID" to agent_id;
ALTER TABLE "agtAgentsInSpace" RENAME COLUMN "dungeonID" to dungeon_id;
ALTER TABLE "agtAgentsInSpace" RENAME COLUMN "solarSystemID" to solar_system_id;
ALTER TABLE "agtAgentsInSpace" RENAME COLUMN "spawnPointID" to spawn_point_id;
ALTER TABLE "agtAgentsInSpace" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "agtResearchAgents" RENAME COLUMN "agentID" to agent_id;
ALTER TABLE "agtResearchAgents" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "certCerts" RENAME COLUMN "certID" to cert_id;
ALTER TABLE "certCerts" RENAME COLUMN "groupID" to group_id;
ALTER TABLE "certMasteries" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "certMasteries" RENAME COLUMN "masteryLevel" to mastery_level;
ALTER TABLE "certMasteries" RENAME COLUMN "certID" to cert_id;
ALTER TABLE "certSkills" RENAME COLUMN "certID" to cert_id;
ALTER TABLE "certSkills" RENAME COLUMN "skillID" to skill_id;
ALTER TABLE "certSkills" RENAME COLUMN "certLevelInt" to cert_level_int;
ALTER TABLE "certSkills" RENAME COLUMN "skillLevel" to skill_level;
ALTER TABLE "certSkills" RENAME COLUMN "certLevelText" to cert_level_text;
ALTER TABLE "chrAncestries" RENAME COLUMN "ancestryID" to ancestry_id;
ALTER TABLE "chrAncestries" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "chrAncestries" RENAME COLUMN "bloodlineID" to bloodline_id;
ALTER TABLE "chrAncestries" RENAME COLUMN "ancestryName" to ancestry_name;
ALTER TABLE "chrAncestries" RENAME COLUMN "shortDescription" to short_description;
ALTER TABLE "chrAttributes" RENAME COLUMN "attributeID" to attribute_id;
ALTER TABLE "chrAttributes" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "chrAttributes" RENAME COLUMN "attributeName" to attribute_name;
ALTER TABLE "chrAttributes" RENAME COLUMN "shortDescription" to short_description;
ALTER TABLE "chrBloodlines" RENAME COLUMN "bloodlineID" to bloodline_id;
ALTER TABLE "chrBloodlines" RENAME COLUMN "corporationID" to corporation_id;
ALTER TABLE "chrBloodlines" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "chrBloodlines" RENAME COLUMN "raceID" to race_id;
ALTER TABLE "chrBloodlines" RENAME COLUMN "shipTypeID" to ship_type_id;
ALTER TABLE "chrBloodlines" RENAME COLUMN "bloodlineName" to bloodline_name;
ALTER TABLE "chrBloodlines" RENAME COLUMN "shortDescription" to short_description;
ALTER TABLE "chrBloodlines" RENAME COLUMN "maleDescription" to male_description;
ALTER TABLE "chrBloodlines" RENAME COLUMN "femaleDescription" to female_description;
ALTER TABLE "chrBloodlines" RENAME COLUMN "shortMaleDescription" to short_male_description;
ALTER TABLE "chrBloodlines" RENAME COLUMN "shortFemaleDescription" to short_female_description;
ALTER TABLE "chrFactions" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "chrFactions" RENAME COLUMN "militiaCorporationID" to militia_corporation_id;
ALTER TABLE "chrFactions" RENAME COLUMN "factionID" to faction_id;
ALTER TABLE "chrFactions" RENAME COLUMN "raceIDs" to race_i_ds;
ALTER TABLE "chrFactions" RENAME COLUMN "solarSystemID" to solar_system_id;
ALTER TABLE "chrFactions" RENAME COLUMN "corporationID" to corporation_id;
ALTER TABLE "chrFactions" RENAME COLUMN "sizeFactor" to size_factor;
ALTER TABLE "chrFactions" RENAME COLUMN "stationCount" to station_count;
ALTER TABLE "chrFactions" RENAME COLUMN "stationSystemCount" to station_system_count;
ALTER TABLE "chrFactions" RENAME COLUMN "factionName" to faction_name;
ALTER TABLE "chrRaces" RENAME COLUMN "raceID" to race_id;
ALTER TABLE "chrRaces" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "chrRaces" RENAME COLUMN "raceName" to race_name;
ALTER TABLE "chrRaces" RENAME COLUMN "shortDescription" to short_description;
ALTER TABLE "crpActivities" RENAME COLUMN "activityID" to activity_id;
ALTER TABLE "crpActivities" RENAME COLUMN "activityName" to activity_name;
ALTER TABLE "crpNPCCorporationDivisions" RENAME COLUMN "corporationID" to corporation_id;
ALTER TABLE "crpNPCCorporationDivisions" RENAME COLUMN "divisionID" to division_id;
ALTER TABLE "crpNPCCorporationResearchFields" RENAME COLUMN "skillID" to skill_id;
ALTER TABLE "crpNPCCorporationResearchFields" RENAME COLUMN "corporationID" to corporation_id;
ALTER TABLE "crpNPCCorporationTrades" RENAME COLUMN "corporationID" to corporation_id;
ALTER TABLE "crpNPCCorporationTrades" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "stationCount" to station_count;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "stationSystemCount" to station_system_count;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "corporationID" to corporation_id;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "solarSystemID" to solar_system_id;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "investorID1" to investor_id1;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "investorShares1" to investor_shares1;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "investorID2" to investor_id2;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "investorShares2" to investor_shares2;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "investorID3" to investor_id3;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "investorShares3" to investor_shares3;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "investorID4" to investor_id4;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "investorShares4" to investor_shares4;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "friendID" to friend_id;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "enemyID" to enemy_id;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "publicShares" to public_shares;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "initialPrice" to initial_price;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "minSecurity" to min_security;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "factionID" to faction_id;
ALTER TABLE "crpNPCCorporations" RENAME COLUMN "sizeFactor" to size_factor;
ALTER TABLE "crpNPCDivisions" RENAME COLUMN "divisionID" to division_id;
ALTER TABLE "crpNPCDivisions" RENAME COLUMN "divisionName" to division_name;
ALTER TABLE "crpNPCDivisions" RENAME COLUMN "leaderType" to leader_type;
ALTER TABLE "dgmAttributeCategories" RENAME COLUMN "categoryID" to category_id;
ALTER TABLE "dgmAttributeCategories" RENAME COLUMN "categoryName" to category_name;
ALTER TABLE "dgmAttributeCategories" RENAME COLUMN "categoryDescription" to category_description;
ALTER TABLE "dgmAttributeTypes" RENAME COLUMN "categoryID" to category_id;
ALTER TABLE "dgmAttributeTypes" RENAME COLUMN "highIsGood" to high_is_good;
ALTER TABLE "dgmAttributeTypes" RENAME COLUMN "attributeID" to attribute_id;
ALTER TABLE "dgmAttributeTypes" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "dgmAttributeTypes" RENAME COLUMN "defaultValue" to default_value;
ALTER TABLE "dgmAttributeTypes" RENAME COLUMN "unitID" to unit_id;
ALTER TABLE "dgmAttributeTypes" RENAME COLUMN "attributeName" to attribute_name;
ALTER TABLE "dgmAttributeTypes" RENAME COLUMN "displayName" to display_name;
ALTER TABLE "dgmEffects" RENAME COLUMN "effectID" to effect_id;
ALTER TABLE "dgmEffects" RENAME COLUMN "electronicChance" to electronic_chance;
ALTER TABLE "dgmEffects" RENAME COLUMN "propulsionChance" to propulsion_chance;
ALTER TABLE "dgmEffects" RENAME COLUMN "npcUsageChanceAttributeID" to npc_usage_chance_attribute_id;
ALTER TABLE "dgmEffects" RENAME COLUMN "npcActivationChanceAttributeID" to npc_activation_chance_attribute_id;
ALTER TABLE "dgmEffects" RENAME COLUMN "fittingUsageChanceAttributeID" to fitting_usage_chance_attribute_id;
ALTER TABLE "dgmEffects" RENAME COLUMN "effectCategory" to effect_category;
ALTER TABLE "dgmEffects" RENAME COLUMN "preExpression" to pre_expression;
ALTER TABLE "dgmEffects" RENAME COLUMN "postExpression" to post_expression;
ALTER TABLE "dgmEffects" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "dgmEffects" RENAME COLUMN "isOffensive" to is_offensive;
ALTER TABLE "dgmEffects" RENAME COLUMN "isAssistance" to is_assistance;
ALTER TABLE "dgmEffects" RENAME COLUMN "durationAttributeID" to duration_attribute_id;
ALTER TABLE "dgmEffects" RENAME COLUMN "trackingSpeedAttributeID" to tracking_speed_attribute_id;
ALTER TABLE "dgmEffects" RENAME COLUMN "dischargeAttributeID" to discharge_attribute_id;
ALTER TABLE "dgmEffects" RENAME COLUMN "rangeAttributeID" to range_attribute_id;
ALTER TABLE "dgmEffects" RENAME COLUMN "falloffAttributeID" to falloff_attribute_id;
ALTER TABLE "dgmEffects" RENAME COLUMN "disallowAutoRepeat" to disallow_auto_repeat;
ALTER TABLE "dgmEffects" RENAME COLUMN "isWarpSafe" to is_warp_safe;
ALTER TABLE "dgmEffects" RENAME COLUMN "rangeChance" to range_chance;
ALTER TABLE "dgmEffects" RENAME COLUMN "effectName" to effect_name;
ALTER TABLE "dgmEffects" RENAME COLUMN "sfxName" to sfx_name;
ALTER TABLE "dgmEffects" RENAME COLUMN "displayName" to display_name;
ALTER TABLE "dgmEffects" RENAME COLUMN "modifierInfo" to modifier_info;
ALTER TABLE "dgmExpressions" RENAME COLUMN "expressionID" to expression_id;
ALTER TABLE "dgmExpressions" RENAME COLUMN "operandID" to operand_id;
ALTER TABLE "dgmExpressions" RENAME COLUMN "expressionTypeID" to expression_type_id;
ALTER TABLE "dgmExpressions" RENAME COLUMN "expressionGroupID" to expression_group_id;
ALTER TABLE "dgmExpressions" RENAME COLUMN "expressionAttributeID" to expression_attribute_id;
ALTER TABLE "dgmExpressions" RENAME COLUMN "expressionValue" to expression_value;
ALTER TABLE "dgmExpressions" RENAME COLUMN "expressionName" to expression_name;
ALTER TABLE "dgmTypeAttributes" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "dgmTypeAttributes" RENAME COLUMN "attributeID" to attribute_id;
ALTER TABLE "dgmTypeAttributes" RENAME COLUMN "valueInt" to value_int;
ALTER TABLE "dgmTypeAttributes" RENAME COLUMN "valueFloat" to value_float;
ALTER TABLE "dgmTypeEffects" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "dgmTypeEffects" RENAME COLUMN "effectID" to effect_id;
ALTER TABLE "dgmTypeEffects" RENAME COLUMN "isDefault" to is_default;
ALTER TABLE "eveGraphics" RENAME COLUMN "graphicID" to graphic_id;
ALTER TABLE "eveGraphics" RENAME COLUMN "sofFactionName" to sof_faction_name;
ALTER TABLE "eveGraphics" RENAME COLUMN "graphicFile" to graphic_file;
ALTER TABLE "eveGraphics" RENAME COLUMN "sofHullName" to sof_hull_name;
ALTER TABLE "eveGraphics" RENAME COLUMN "sofRaceName" to sof_race_name;
ALTER TABLE "eveIcons" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "eveIcons" RENAME COLUMN "iconFile" to icon_file;
ALTER TABLE "eveUnits" RENAME COLUMN "unitID" to unit_id;
ALTER TABLE "eveUnits" RENAME COLUMN "unitName" to unit_name;
ALTER TABLE "eveUnits" RENAME COLUMN "displayName" to display_name;
ALTER TABLE "industryActivity" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "industryActivity" RENAME COLUMN "activityID" to activity_id;
ALTER TABLE "industryActivityMaterials" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "industryActivityMaterials" RENAME COLUMN "activityID" to activity_id;
ALTER TABLE "industryActivityMaterials" RENAME COLUMN "materialTypeID" to material_type_id;
ALTER TABLE "industryActivityProbabilities" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "industryActivityProbabilities" RENAME COLUMN "activityID" to activity_id;
ALTER TABLE "industryActivityProbabilities" RENAME COLUMN "productTypeID" to product_type_id;
ALTER TABLE "industryActivityProducts" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "industryActivityProducts" RENAME COLUMN "activityID" to activity_id;
ALTER TABLE "industryActivityProducts" RENAME COLUMN "productTypeID" to product_type_id;
ALTER TABLE "industryActivityRaces" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "industryActivityRaces" RENAME COLUMN "activityID" to activity_id;
ALTER TABLE "industryActivityRaces" RENAME COLUMN "productTypeID" to product_type_id;
ALTER TABLE "industryActivityRaces" RENAME COLUMN "raceID" to race_id;
ALTER TABLE "industryActivitySkills" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "industryActivitySkills" RENAME COLUMN "activityID" to activity_id;
ALTER TABLE "industryActivitySkills" RENAME COLUMN "skillID" to skill_id;
ALTER TABLE "industryBlueprints" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "industryBlueprints" RENAME COLUMN "maxProductionLimit" to max_production_limit;
ALTER TABLE "invCategories" RENAME COLUMN "categoryID" to category_id;
ALTER TABLE "invCategories" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "invCategories" RENAME COLUMN "categoryName" to category_name;
ALTER TABLE "invContrabandTypes" RENAME COLUMN "factionID" to faction_id;
ALTER TABLE "invContrabandTypes" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "invContrabandTypes" RENAME COLUMN "standingLoss" to standing_loss;
ALTER TABLE "invContrabandTypes" RENAME COLUMN "confiscateMinSec" to confiscate_min_sec;
ALTER TABLE "invContrabandTypes" RENAME COLUMN "fineByValue" to fine_by_value;
ALTER TABLE "invContrabandTypes" RENAME COLUMN "attackMinSec" to attack_min_sec;
ALTER TABLE "invControlTowerResourcePurposes" RENAME COLUMN "purposeText" to purpose_text;
ALTER TABLE "invControlTowerResources" RENAME COLUMN "controlTowerTypeID" to control_tower_type_id;
ALTER TABLE "invControlTowerResources" RENAME COLUMN "resourceTypeID" to resource_type_id;
ALTER TABLE "invControlTowerResources" RENAME COLUMN "minSecurityLevel" to min_security_level;
ALTER TABLE "invControlTowerResources" RENAME COLUMN "factionID" to faction_id;
ALTER TABLE "invFlags" RENAME COLUMN "flagID" to flag_id;
ALTER TABLE "invFlags" RENAME COLUMN "orderID" to order_id;
ALTER TABLE "invFlags" RENAME COLUMN "flagName" to flag_name;
ALTER TABLE "invFlags" RENAME COLUMN "flagText" to flag_text;
ALTER TABLE "invGroups" RENAME COLUMN "categoryID" to category_id;
ALTER TABLE "invGroups" RENAME COLUMN "groupID" to group_id;
ALTER TABLE "invGroups" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "invGroups" RENAME COLUMN "useBasePrice" to use_base_price;
ALTER TABLE "invGroups" RENAME COLUMN "fittableNonSingleton" to fittable_non_singleton;
ALTER TABLE "invGroups" RENAME COLUMN "groupName" to group_name;
ALTER TABLE "invItems" RENAME COLUMN "itemID" to item_id;
ALTER TABLE "invItems" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "invItems" RENAME COLUMN "ownerID" to owner_id;
ALTER TABLE "invItems" RENAME COLUMN "locationID" to location_id;
ALTER TABLE "invItems" RENAME COLUMN "flagID" to flag_id;
ALTER TABLE "invMarketGroups" RENAME COLUMN "marketGroupID" to market_group_id;
ALTER TABLE "invMarketGroups" RENAME COLUMN "parentGroupID" to parent_group_id;
ALTER TABLE "invMarketGroups" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "invMarketGroups" RENAME COLUMN "hasTypes" to has_types;
ALTER TABLE "invMarketGroups" RENAME COLUMN "marketGroupName" to market_group_name;
ALTER TABLE "invMetaGroups" RENAME COLUMN "metaGroupID" to meta_group_id;
ALTER TABLE "invMetaGroups" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "invMetaGroups" RENAME COLUMN "metaGroupName" to meta_group_name;
ALTER TABLE "invMetaTypes" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "invMetaTypes" RENAME COLUMN "parentTypeID" to parent_type_id;
ALTER TABLE "invMetaTypes" RENAME COLUMN "metaGroupID" to meta_group_id;
ALTER TABLE "invNames" RENAME COLUMN "itemID" to item_id;
ALTER TABLE "invNames" RENAME COLUMN "itemName" to item_name;
ALTER TABLE "invPositions" RENAME COLUMN "itemID" to item_id;
ALTER TABLE "invTraits" RENAME COLUMN "traitID" to trait_id;
ALTER TABLE "invTraits" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "invTraits" RENAME COLUMN "skillID" to skill_id;
ALTER TABLE "invTraits" RENAME COLUMN "unitID" to unit_id;
ALTER TABLE "invTraits" RENAME COLUMN "bonusText" to bonus_text;
ALTER TABLE "invTypeMaterials" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "invTypeMaterials" RENAME COLUMN "materialTypeID" to material_type_id;
ALTER TABLE "invTypeReactions" RENAME COLUMN "reactionTypeID" to reaction_type_id;
ALTER TABLE "invTypeReactions" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "invTypes" RENAME COLUMN "graphicID" to graphic_id;
ALTER TABLE "invTypes" RENAME COLUMN "groupID" to group_id;
ALTER TABLE "invTypes" RENAME COLUMN "soundID" to sound_id;
ALTER TABLE "invTypes" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "invTypes" RENAME COLUMN "portionSize" to portion_size;
ALTER TABLE "invTypes" RENAME COLUMN "raceID" to race_id;
ALTER TABLE "invTypes" RENAME COLUMN "basePrice" to base_price;
ALTER TABLE "invTypes" RENAME COLUMN "marketGroupID" to market_group_id;
ALTER TABLE "invTypes" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "invTypes" RENAME COLUMN "typeName" to type_name;
ALTER TABLE "invUniqueNames" RENAME COLUMN "itemID" to item_id;
ALTER TABLE "invUniqueNames" RENAME COLUMN "groupID" to group_id;
ALTER TABLE "invUniqueNames" RENAME COLUMN "itemName" to item_name;
ALTER TABLE "invVolumes" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "mapCelestialGraphics" RENAME COLUMN "celestialID" to celestial_id;
ALTER TABLE "mapCelestialGraphics" RENAME COLUMN "heightMap1" to height_map1;
ALTER TABLE "mapCelestialGraphics" RENAME COLUMN "heightMap2" to height_map2;
ALTER TABLE "mapCelestialGraphics" RENAME COLUMN "shaderPreset" to shader_preset;
ALTER TABLE "mapCelestialStatistics" RENAME COLUMN "celestialID" to celestial_id;
ALTER TABLE "mapCelestialStatistics" RENAME COLUMN "orbitRadius" to orbit_radius;
ALTER TABLE "mapCelestialStatistics" RENAME COLUMN "massDust" to mass_dust;
ALTER TABLE "mapCelestialStatistics" RENAME COLUMN "massGas" to mass_gas;
ALTER TABLE "mapCelestialStatistics" RENAME COLUMN "surfaceGravity" to surface_gravity;
ALTER TABLE "mapCelestialStatistics" RENAME COLUMN "escapeVelocity" to escape_velocity;
ALTER TABLE "mapCelestialStatistics" RENAME COLUMN "orbitPeriod" to orbit_period;
ALTER TABLE "mapCelestialStatistics" RENAME COLUMN "rotationRate" to rotation_rate;
ALTER TABLE "mapCelestialStatistics" RENAME COLUMN "spectralClass" to spectral_class;
ALTER TABLE "mapConstellationJumps" RENAME COLUMN "fromRegionID" to from_region_id;
ALTER TABLE "mapConstellationJumps" RENAME COLUMN "fromConstellationID" to from_constellation_id;
ALTER TABLE "mapConstellationJumps" RENAME COLUMN "toConstellationID" to to_constellation_id;
ALTER TABLE "mapConstellationJumps" RENAME COLUMN "toRegionID" to to_region_id;
ALTER TABLE "mapConstellations" RENAME COLUMN "constellationID" to constellation_id;
ALTER TABLE "mapConstellations" RENAME COLUMN "regionID" to region_id;
ALTER TABLE "mapConstellations" RENAME COLUMN "xMin" to x_min;
ALTER TABLE "mapConstellations" RENAME COLUMN "xMax" to x_max;
ALTER TABLE "mapConstellations" RENAME COLUMN "yMin" to y_min;
ALTER TABLE "mapConstellations" RENAME COLUMN "yMax" to y_max;
ALTER TABLE "mapConstellations" RENAME COLUMN "zMin" to z_min;
ALTER TABLE "mapConstellations" RENAME COLUMN "zMax" to z_max;
ALTER TABLE "mapConstellations" RENAME COLUMN "factionID" to faction_id;
ALTER TABLE "mapConstellations" RENAME COLUMN "constellationName" to constellation_name;
ALTER TABLE "mapDenormalize" RENAME COLUMN "orbitIndex" to orbit_index;
ALTER TABLE "mapDenormalize" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "mapDenormalize" RENAME COLUMN "groupID" to group_id;
ALTER TABLE "mapDenormalize" RENAME COLUMN "solarSystemID" to solar_system_id;
ALTER TABLE "mapDenormalize" RENAME COLUMN "constellationID" to constellation_id;
ALTER TABLE "mapDenormalize" RENAME COLUMN "regionID" to region_id;
ALTER TABLE "mapDenormalize" RENAME COLUMN "orbitID" to orbit_id;
ALTER TABLE "mapDenormalize" RENAME COLUMN "itemID" to item_id;
ALTER TABLE "mapDenormalize" RENAME COLUMN "celestialIndex" to celestial_index;
ALTER TABLE "mapDenormalize" RENAME COLUMN "itemName" to item_name;
ALTER TABLE "mapJumps" RENAME COLUMN "stargateID" to stargate_id;
ALTER TABLE "mapJumps" RENAME COLUMN "destinationID" to destination_id;
ALTER TABLE "mapLandmarks" RENAME COLUMN "iconID" to icon_id;
ALTER TABLE "mapLandmarks" RENAME COLUMN "landmarkID" to landmark_id;
ALTER TABLE "mapLandmarks" RENAME COLUMN "locationID" to location_id;
ALTER TABLE "mapLandmarks" RENAME COLUMN "landmarkName" to landmark_name;
ALTER TABLE "mapLocationScenes" RENAME COLUMN "locationID" to location_id;
ALTER TABLE "mapLocationScenes" RENAME COLUMN "graphicID" to graphic_id;
ALTER TABLE "mapLocationWormholeClasses" RENAME COLUMN "locationID" to location_id;
ALTER TABLE "mapLocationWormholeClasses" RENAME COLUMN "wormholeClassID" to wormhole_class_id;
ALTER TABLE "mapRegionJumps" RENAME COLUMN "fromRegionID" to from_region_id;
ALTER TABLE "mapRegionJumps" RENAME COLUMN "toRegionID" to to_region_id;
ALTER TABLE "mapRegions" RENAME COLUMN "regionID" to region_id;
ALTER TABLE "mapRegions" RENAME COLUMN "xMin" to x_min;
ALTER TABLE "mapRegions" RENAME COLUMN "xMax" to x_max;
ALTER TABLE "mapRegions" RENAME COLUMN "yMin" to y_min;
ALTER TABLE "mapRegions" RENAME COLUMN "yMax" to y_max;
ALTER TABLE "mapRegions" RENAME COLUMN "zMin" to z_min;
ALTER TABLE "mapRegions" RENAME COLUMN "zMax" to z_max;
ALTER TABLE "mapRegions" RENAME COLUMN "factionID" to faction_id;
ALTER TABLE "mapRegions" RENAME COLUMN "regionName" to region_name;
ALTER TABLE "mapSolarSystemJumps" RENAME COLUMN "fromRegionID" to from_region_id;
ALTER TABLE "mapSolarSystemJumps" RENAME COLUMN "fromConstellationID" to from_constellation_id;
ALTER TABLE "mapSolarSystemJumps" RENAME COLUMN "fromSolarSystemID" to from_solar_system_id;
ALTER TABLE "mapSolarSystemJumps" RENAME COLUMN "toSolarSystemID" to to_solar_system_id;
ALTER TABLE "mapSolarSystemJumps" RENAME COLUMN "toConstellationID" to to_constellation_id;
ALTER TABLE "mapSolarSystemJumps" RENAME COLUMN "toRegionID" to to_region_id;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "regionID" to region_id;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "constellationID" to constellation_id;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "solarSystemID" to solar_system_id;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "sunTypeID" to sun_type_id;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "xMin" to x_min;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "xMax" to x_max;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "yMin" to y_min;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "yMax" to y_max;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "zMin" to z_min;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "zMax" to z_max;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "factionID" to faction_id;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "solarSystemName" to solar_system_name;
ALTER TABLE "mapSolarSystems" RENAME COLUMN "securityClass" to security_class;
ALTER TABLE "mapUniverse" RENAME COLUMN "universeID" to universe_id;
ALTER TABLE "mapUniverse" RENAME COLUMN "xMin" to x_min;
ALTER TABLE "mapUniverse" RENAME COLUMN "xMax" to x_max;
ALTER TABLE "mapUniverse" RENAME COLUMN "yMin" to y_min;
ALTER TABLE "mapUniverse" RENAME COLUMN "yMax" to y_max;
ALTER TABLE "mapUniverse" RENAME COLUMN "zMin" to z_min;
ALTER TABLE "mapUniverse" RENAME COLUMN "zMax" to z_max;
ALTER TABLE "mapUniverse" RENAME COLUMN "universeName" to universe_name;
ALTER TABLE "planetSchematics" RENAME COLUMN "schematicID" to schematic_id;
ALTER TABLE "planetSchematics" RENAME COLUMN "cycleTime" to cycle_time;
ALTER TABLE "planetSchematics" RENAME COLUMN "schematicName" to schematic_name;
ALTER TABLE "planetSchematicsPinMap" RENAME COLUMN "schematicID" to schematic_id;
ALTER TABLE "planetSchematicsPinMap" RENAME COLUMN "pinTypeID" to pin_type_id;
ALTER TABLE "planetSchematicsTypeMap" RENAME COLUMN "schematicID" to schematic_id;
ALTER TABLE "planetSchematicsTypeMap" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "planetSchematicsTypeMap" RENAME COLUMN "isInput" to is_input;
ALTER TABLE "ramActivities" RENAME COLUMN "activityID" to activity_id;
ALTER TABLE "ramActivities" RENAME COLUMN "activityName" to activity_name;
ALTER TABLE "ramActivities" RENAME COLUMN "iconNo" to icon_no;
ALTER TABLE "ramAssemblyLineStations" RENAME COLUMN "stationID" to station_id;
ALTER TABLE "ramAssemblyLineStations" RENAME COLUMN "assemblyLineTypeID" to assembly_line_type_id;
ALTER TABLE "ramAssemblyLineStations" RENAME COLUMN "stationTypeID" to station_type_id;
ALTER TABLE "ramAssemblyLineStations" RENAME COLUMN "ownerID" to owner_id;
ALTER TABLE "ramAssemblyLineStations" RENAME COLUMN "solarSystemID" to solar_system_id;
ALTER TABLE "ramAssemblyLineStations" RENAME COLUMN "regionID" to region_id;
ALTER TABLE "ramAssemblyLineTypeDetailPerCategory" RENAME COLUMN "assemblyLineTypeID" to assembly_line_type_id;
ALTER TABLE "ramAssemblyLineTypeDetailPerCategory" RENAME COLUMN "categoryID" to category_id;
ALTER TABLE "ramAssemblyLineTypeDetailPerCategory" RENAME COLUMN "timeMultiplier" to time_multiplier;
ALTER TABLE "ramAssemblyLineTypeDetailPerCategory" RENAME COLUMN "materialMultiplier" to material_multiplier;
ALTER TABLE "ramAssemblyLineTypeDetailPerCategory" RENAME COLUMN "costMultiplier" to cost_multiplier;
ALTER TABLE "ramAssemblyLineTypeDetailPerGroup" RENAME COLUMN "assemblyLineTypeID" to assembly_line_type_id;
ALTER TABLE "ramAssemblyLineTypeDetailPerGroup" RENAME COLUMN "groupID" to group_id;
ALTER TABLE "ramAssemblyLineTypeDetailPerGroup" RENAME COLUMN "timeMultiplier" to time_multiplier;
ALTER TABLE "ramAssemblyLineTypeDetailPerGroup" RENAME COLUMN "materialMultiplier" to material_multiplier;
ALTER TABLE "ramAssemblyLineTypeDetailPerGroup" RENAME COLUMN "costMultiplier" to cost_multiplier;
ALTER TABLE "ramAssemblyLineTypes" RENAME COLUMN "minCostPerHour" to min_cost_per_hour;
ALTER TABLE "ramAssemblyLineTypes" RENAME COLUMN "activityID" to activity_id;
ALTER TABLE "ramAssemblyLineTypes" RENAME COLUMN "assemblyLineTypeID" to assembly_line_type_id;
ALTER TABLE "ramAssemblyLineTypes" RENAME COLUMN "baseTimeMultiplier" to base_time_multiplier;
ALTER TABLE "ramAssemblyLineTypes" RENAME COLUMN "baseMaterialMultiplier" to base_material_multiplier;
ALTER TABLE "ramAssemblyLineTypes" RENAME COLUMN "baseCostMultiplier" to base_cost_multiplier;
ALTER TABLE "ramAssemblyLineTypes" RENAME COLUMN "assemblyLineTypeName" to assembly_line_type_name;
ALTER TABLE "ramInstallationTypeContents" RENAME COLUMN "installationTypeID" to installation_type_id;
ALTER TABLE "ramInstallationTypeContents" RENAME COLUMN "assemblyLineTypeID" to assembly_line_type_id;
ALTER TABLE "skinLicense" RENAME COLUMN "licenseTypeID" to license_type_id;
ALTER TABLE "skinLicense" RENAME COLUMN "skinID" to skin_id;
ALTER TABLE "skinMaterials" RENAME COLUMN "skinMaterialID" to skin_material_id;
ALTER TABLE "skinMaterials" RENAME COLUMN "displayNameID" to display_name_id;
ALTER TABLE "skinMaterials" RENAME COLUMN "materialSetID" to material_set_id;
ALTER TABLE "skinShip" RENAME COLUMN "skinID" to skin_id;
ALTER TABLE "skinShip" RENAME COLUMN "typeID" to type_id;
ALTER TABLE "skins" RENAME COLUMN "skinID" to skin_id;
ALTER TABLE "skins" RENAME COLUMN "internalName" to internal_name;
ALTER TABLE "skins" RENAME COLUMN "skinMaterialID" to skin_material_in;
ALTER TABLE "staOperationServices" RENAME COLUMN "operationID" to operation_id;
ALTER TABLE "staOperationServices" RENAME COLUMN "serviceID" to service_id;
ALTER TABLE "staOperations" RENAME COLUMN "joveStationTypeID" to jove_station_type_id;
ALTER TABLE "staOperations" RENAME COLUMN "operationID" to operation_id;
ALTER TABLE "staOperations" RENAME COLUMN "gallenteStationTypeID" to gallente_station_type_id;
ALTER TABLE "staOperations" RENAME COLUMN "activityID" to activity_id;
ALTER TABLE "staOperations" RENAME COLUMN "caldariStationTypeID" to caldari_station_type_id;
ALTER TABLE "staOperations" RENAME COLUMN "minmatarStationTypeID" to minmatar_station_type_id;
ALTER TABLE "staOperations" RENAME COLUMN "amarrStationTypeID" to amarr_station_type_id;
ALTER TABLE "staOperations" RENAME COLUMN "operationName" to operation_name;
ALTER TABLE "staServices" RENAME COLUMN "serviceID" to service_id;
ALTER TABLE "staServices" RENAME COLUMN "serviceName" to service_name;
ALTER TABLE "staStationTypes" RENAME COLUMN "stationTypeID" to station_type_id;
ALTER TABLE "staStationTypes" RENAME COLUMN "dockEntryX" to dock_entry_x;
ALTER TABLE "staStationTypes" RENAME COLUMN "dockEntryY" to dock_entry_y;
ALTER TABLE "staStationTypes" RENAME COLUMN "dockEntryZ" to dock_entry_z;
ALTER TABLE "staStationTypes" RENAME COLUMN "dockOrientationX" to dock_orientation_x;
ALTER TABLE "staStationTypes" RENAME COLUMN "dockOrientationY" to dock_orientation_y;
ALTER TABLE "staStationTypes" RENAME COLUMN "dockOrientationZ" to dock_orientation_z;
ALTER TABLE "staStationTypes" RENAME COLUMN "operationID" to operation_id;
ALTER TABLE "staStationTypes" RENAME COLUMN "officeSlots" to office_slots;
ALTER TABLE "staStationTypes" RENAME COLUMN "reprocessingEfficiency" to reprocessing_efficiency;
ALTER TABLE "staStations" RENAME COLUMN "reprocessingHangarFlag" to reprocessing_hangar_flag;
ALTER TABLE "staStations" RENAME COLUMN "dockingCostPerVolume" to docking_cost_per_volume;
ALTER TABLE "staStations" RENAME COLUMN "maxShipVolumeDockable" to max_ship_volume_dockable;
ALTER TABLE "staStations" RENAME COLUMN "officeRentalCost" to office_rental_cost;
ALTER TABLE "staStations" RENAME COLUMN "operationID" to operation_id;
ALTER TABLE "staStations" RENAME COLUMN "stationTypeID" to station_type_id;
ALTER TABLE "staStations" RENAME COLUMN "corporationID" to corporation_id;
ALTER TABLE "staStations" RENAME COLUMN "solarSystemID" to solar_system_id;
ALTER TABLE "staStations" RENAME COLUMN "constellationID" to constellation_id;
ALTER TABLE "staStations" RENAME COLUMN "regionID" to region_id;
ALTER TABLE "staStations" RENAME COLUMN "stationID" to station_id;
ALTER TABLE "staStations" RENAME COLUMN "reprocessingEfficiency" to reprocessing_efficiency;
ALTER TABLE "staStations" RENAME COLUMN "reprocessingStationsTake" to reprocessing_stations_take;
ALTER TABLE "staStations" RENAME COLUMN "stationName" to station_name;
ALTER TABLE "translationTables" RENAME COLUMN "tcGroupID" to tc_group_id;
ALTER TABLE "translationTables" RENAME COLUMN "tcID" to tc_id;
ALTER TABLE "translationTables" RENAME COLUMN "sourceTable" to source_table;
ALTER TABLE "translationTables" RENAME COLUMN "destinationTable" to destination_table;
ALTER TABLE "translationTables" RENAME COLUMN "translatedKey" to translated_key;
ALTER TABLE "trnTranslationColumns" RENAME COLUMN "tcGroupID" to tc_group_id;
ALTER TABLE "trnTranslationColumns" RENAME COLUMN "tcID" to tc_id;
ALTER TABLE "trnTranslationColumns" RENAME COLUMN "tableName" to table_name;
ALTER TABLE "trnTranslationColumns" RENAME COLUMN "columnName" to column_name;
ALTER TABLE "trnTranslationColumns" RENAME COLUMN "masterID" to master_id;
ALTER TABLE "trnTranslationLanguages" RENAME COLUMN "numericLanguageID" to numeric_language_id;
ALTER TABLE "trnTranslationLanguages" RENAME COLUMN "languageID" to language_id;
ALTER TABLE "trnTranslationLanguages" RENAME COLUMN "languageName" to language_name;
ALTER TABLE "trnTranslations" RENAME COLUMN "tcID" to tc_id;
ALTER TABLE "trnTranslations" RENAME COLUMN "keyID" to key_id;
ALTER TABLE "trnTranslations" RENAME COLUMN "languageID" to language_id;
ALTER TABLE "warCombatZoneSystems" RENAME COLUMN "solarSystemID" to solar_system_id;
ALTER TABLE "warCombatZoneSystems" RENAME COLUMN "combatZoneID" to combat_zone_id;
ALTER TABLE "warCombatZones" RENAME COLUMN "combatZoneID" to combat_zone_id;
ALTER TABLE "warCombatZones" RENAME COLUMN "factionID" to faction_id;
ALTER TABLE "warCombatZones" RENAME COLUMN "centerSystemID" to center_system_id;
ALTER TABLE "warCombatZones" RENAME COLUMN "combatZoneName" to combat_zone_name;

ALTER TABLE "agtAgentTypes" RENAME TO agt_agent_types;
ALTER TABLE "agtAgents" RENAME TO agt_agents;
ALTER TABLE "agtAgentsInSpace" RENAME TO agt_agents_in_space;
ALTER TABLE "agtResearchAgents" RENAME TO agt_research_agents;
ALTER TABLE "certCerts" RENAME TO cert_certs;
ALTER TABLE "certMasteries" RENAME TO cert_masteries;
ALTER TABLE "certSkills" RENAME TO cert_skills;
ALTER TABLE "chrAncestries" RENAME TO chr_ancestries;
ALTER TABLE "chrAttributes" RENAME TO chr_attributes;
ALTER TABLE "chrBloodlines" RENAME TO chr_bloodlines;
ALTER TABLE "chrFactions" RENAME TO chr_factions;
ALTER TABLE "chrRaces" RENAME TO chr_races;
ALTER TABLE "crpActivities" RENAME TO crp_activities;
ALTER TABLE "crpNPCCorporationDivisions" RENAME TO crp_npc_corporation_divisions;
ALTER TABLE "crpNPCCorporationResearchFields" RENAME TO crp_npc_corporation_research_fields;
ALTER TABLE "crpNPCCorporationTrades" RENAME TO crp_npc_corporation_trades;
ALTER TABLE "crpNPCCorporations" RENAME TO crp_npc_corporations;
ALTER TABLE "crpNPCDivisions" RENAME TO crp_npc_divisions;
ALTER TABLE "dgmAttributeCategories" RENAME TO dgm_attribute_categories;
ALTER TABLE "dgmAttributeTypes" RENAME TO dgm_attribute_types;
ALTER TABLE "dgmEffects" RENAME TO dgm_effects;
ALTER TABLE "dgmExpressions" RENAME TO dgm_expressions;
ALTER TABLE "dgmTypeAttributes" RENAME TO dgm_type_attributes;
ALTER TABLE "dgmTypeEffects" RENAME TO dgm_type_effects;
ALTER TABLE "eveGraphics" RENAME TO eve_graphics;
ALTER TABLE "eveIcons" RENAME TO eve_icons;
ALTER TABLE "eveUnits" RENAME TO eve_units;
ALTER TABLE "industryActivity" RENAME TO industry_activity;
ALTER TABLE "industryActivityMaterials" RENAME TO industry_activity_materials;
ALTER TABLE "industryActivityProbabilities" RENAME TO industry_activity_probabilities;
ALTER TABLE "industryActivityProducts" RENAME TO industry_activity_products;
ALTER TABLE "industryActivityRaces" RENAME TO industry_activity_races;
ALTER TABLE "industryActivitySkills" RENAME TO industry_activity_skills;
ALTER TABLE "industryBlueprints" RENAME TO industry_blueprints;
ALTER TABLE "invCategories" RENAME TO inv_categories;
ALTER TABLE "invContrabandTypes" RENAME TO inv_contraband_types;
ALTER TABLE "invControlTowerResourcePurposes" RENAME TO inv_control_tower_resource_purposes;
ALTER TABLE "invControlTowerResources" RENAME TO inv_control_tower_resources;
ALTER TABLE "invFlags" RENAME TO inv_flags;
ALTER TABLE "invGroups" RENAME TO inv_groups;
ALTER TABLE "invItems" RENAME TO inv_items;
ALTER TABLE "invMarketGroups" RENAME TO inv_market_groups;
ALTER TABLE "invMetaGroups" RENAME TO inv_meta_groups;
ALTER TABLE "invMetaTypes" RENAME TO inv_meta_types;
ALTER TABLE "invNames" RENAME TO inv_names;
ALTER TABLE "invPositions" RENAME TO inv_positions;
ALTER TABLE "invTraits" RENAME TO inv_traits;
ALTER TABLE "invTypeMaterials" RENAME TO inv_type_materials;
ALTER TABLE "invTypeReactions" RENAME TO inv_type_reactions;
ALTER TABLE "invTypes" RENAME TO inv_types;
ALTER TABLE "invUniqueNames" RENAME TO inv_unique_names;
ALTER TABLE "invVolumes" RENAME TO inv_volumes;
ALTER TABLE "mapCelestialGraphics" RENAME TO map_celestial_graphics;
ALTER TABLE "mapCelestialStatistics" RENAME TO map_celestial_statistics;
ALTER TABLE "mapConstellationJumps" RENAME TO map_constellation_jumps;
ALTER TABLE "mapConstellations" RENAME TO map_constellations;
ALTER TABLE "mapDenormalize" RENAME TO map_denormalize;
ALTER TABLE "mapJumps" RENAME TO map_jumps;
ALTER TABLE "mapLandmarks" RENAME TO map_landmarks;
ALTER TABLE "mapLocationScenes" RENAME TO map_location_scenes;
ALTER TABLE "mapLocationWormholeClasses" RENAME TO map_location_wormhole_classes;
ALTER TABLE "mapRegionJumps" RENAME TO map_region_jumps;
ALTER TABLE "mapRegions" RENAME TO map_regions;
ALTER TABLE "mapSolarSystemJumps" RENAME TO map_solar_system_jumps;
ALTER TABLE "mapSolarSystems" RENAME TO map_solar_systems;
ALTER TABLE "mapUniverse" RENAME TO map_universe;
ALTER TABLE "planetSchematics" RENAME TO planet_schematics;
ALTER TABLE "planetSchematicsPinMap" RENAME TO planet_schematics_pin_map;
ALTER TABLE "planetSchematicsTypeMap" RENAME TO planet_schematics_type_map;
ALTER TABLE "ramActivities" RENAME TO ram_activities;
ALTER TABLE "ramAssemblyLineStations" RENAME TO ram_assembly_line_stations;
ALTER TABLE "ramAssemblyLineTypeDetailPerCategory" RENAME TO ram_assembly_line_type_detail_per_category;
ALTER TABLE "ramAssemblyLineTypeDetailPerGroup" RENAME TO ram_assembly_line_type_detail_per_group;
ALTER TABLE "ramAssemblyLineTypes" RENAME TO ram_assembly_line_types;
ALTER TABLE "ramInstallationTypeContents" RENAME TO ram_installation_type_contents;
ALTER TABLE "skinLicense" RENAME TO skin_license;
ALTER TABLE "skinMaterials" RENAME TO skin_materials;
ALTER TABLE "skinShip" RENAME TO skin_ship;
ALTER TABLE "staOperationServices" RENAME TO sta_operation_services;
ALTER TABLE "staOperations" RENAME TO sta_operations;
ALTER TABLE "staServices" RENAME TO sta_services;
ALTER TABLE "staStationTypes" RENAME TO sta_station_types;
ALTER TABLE "staStations" RENAME TO sta_stations;
ALTER TABLE "translationTables" RENAME TO translation_tables;
ALTER TABLE "trnTranslationColumns" RENAME TO trn_translation_columns;
ALTER TABLE "trnTranslationLanguages" RENAME TO trn_translation_languages;
ALTER TABLE "trnTranslations" RENAME TO trn_translations;
ALTER TABLE "warCombatZoneSystems" RENAME TO war_combat_zone_systems;
ALTER TABLE "warCombatZones" RENAME TO war_combat_zones;
